//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityHolaMundo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EjerciciosTichEntities1 : DbContext
    {
        public EjerciciosTichEntities1()
            : base("name=EjerciciosTichEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumnos> Alumnos { get; set; }
        public virtual DbSet<AlumnosBaja> AlumnosBaja { get; set; }
        public virtual DbSet<CatCursos> CatCursos { get; set; }
        public virtual DbSet<Cursos> Cursos { get; set; }
        public virtual DbSet<CursosAlumnos> CursosAlumnos { get; set; }
        public virtual DbSet<CursosInstructores> CursosInstructores { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<EstatusAlumnos> EstatusAlumnos { get; set; }
        public virtual DbSet<Instructores> Instructores { get; set; }
        public virtual DbSet<Saldos> Saldos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TablaISR> TablaISR { get; set; }
        public virtual DbSet<Transacciones> Transacciones { get; set; }
        public virtual DbSet<AlumnosHgo> AlumnosHgo { get; set; }
    }
}
